apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-in-python-webapp-deployment
  labels:
    app: microservices-in-python-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservices-in-python-webapp
  template:
    metadata:
      labels:
        app: microservices-in-python-webapp
    spec:
      containers:
      - name: microservices-in-python-webapp
        image: microservices-in-python-webapp:1.0
        ports:
        - containerPort: 5000